### ISSUE TITLE
Question: Request for collaboration

### ISSUE THREAD

**Issue by fabgio** [openwebnet/openwebnet-android#62]
Hi Niqdev! 
Hanging around github, I spotted the  openwebnet-android project. I have been developing a similar project   since two years. Project  location is https://github.com/gfabiani/DomoHome 
So I was wondering if you might be interested in a collaboration.

**Comment by niqdev** [comment]
Hi @fabgio,
you are very welcome of course and there is plenty of room for improvement!
Are you interested in something particular? Have you seen any issue that suits more to you?

Actually I started working on [Sound System](https://github.com/openwebnet/rx-openwebnet/blob/master/lib/src/main/java/com/github/niqdev/openwebnet/message/SoundSystem.java) but I stopped and asked directly to BTicino if should I use WHO 22 to manage amplifier as well, it seems that only 16 do it currently.

So a couple of days ago I started to work on [Scenario](https://github.com/openwebnet/rx-openwebnet/blob/feature/scenario/lib/src/main/java/com/github/niqdev/openwebnet/message/Scene.java) on this branch, should be finished but I haven't tested it yet and of course needs to be implemented in the app.

I was also looking at this [issue](https://github.com/openwebnet/openwebnet-android/issues/58) today and I sent an email to the user that requested me, to have more information because is not so clear and I connect from remote using a VPN.

And also today I was debugging with another user the light. I didn't opened the issue yet, but it seems that some gateway when request the status of the light doesn't return always the value but only an ACK and so the user couldn't swith the light.

These are the issue on which I was working, so just let me know in what are you interested in and I'll give you more details. I think also that if you are interested on the issue on Android Wear you are free to take it.

Moreover, do you know Scala or React?
Probably I think I will write also a backend to manage the backup and the configuration from a webapp. But for now I think is important to finish the app before everything else.

Thanks,
Nik

**Comment by fabgio** [comment]
Hi Nik! Sorry for the late answer but  I have been away for a while. I 
needed time to understand the code as well.

I have studied the Realm documentation and I find I could tackle the 
issue 48 search by name(is that still open isn't it)?

I do not know Scala or React. Still I look forward to learn Scala (I 
have watched Martin Odersky's book)

How can I fork the repository so that I can submit implementations?

Many thanks
Giovanni
PS What is your native language?
Il 03/09/2016 16:03, niqdev ha scritto:

**Comment by niqdev** [comment]
Hi Giovanni,
no problem!
I've just sent an invitation to become member of the team so I can assign the issue.

Yes the 48 is still open, I'd like to have something like [this](https://github.com/DenisMondon/material-design-library/tree/master/sample/src/main/java/com/blunderer/materialdesignlibrary/sample/searchbar) but feel free to suggest your own implementation and of course check the official docs. Moreover let me know before start how would you like to proceed, so we can discuss which could be the best way to implement and integrate it.

I've nearly completed also the 54, i'm only missing few tests.

Great for Scala, but we'll discuss it later.

Here the [guidelines](https://github.com/openwebnet/openwebnet-android/blob/master/CONTRIBUTING.md) and a [gist](https://gist.github.com/niqdev/2d075acf85095fa6aa1ae14bad408785) to keep your repo alway up to date with the last changes.
The idea is to keep master aligned with the version in the store, development as the reference branch and you should always create your own branch.

Anyway, I'm italian!
Thanks,
Nik

**Comment by niqdev** [comment]
@fabgio I suggest to update your forked repo with the latest change on development before modify the code or merge your feature branch or make a pull request on development.
I have done 2 releases today and probably another one later. 
If you have any problems or you need any help just contact me!

**Comment by niqdev** [comment]
@fabgio I will close it and let's discuss the specific problem in the related issue.
Thanks again for your interest!
Nik
